#!/usr/bin/env bash
# sync-container-env-to-terraform.sh
#
# Copy selected keys from repo .env into terraform/container_env.{prod,dev}.tfvars
# so `terraform apply` can push them to the OCI container (CLI, no Console).
#
# Usage:
#   ./scripts/oci/sync-container-env-to-terraform.sh          # prod → .env
#   ./scripts/oci/sync-container-env-to-terraform-dev.sh    # dev → .env.dev
#
# Does NOT copy ORDS_BASE_URL (Terraform sets that from ADB).
# Does NOT set IDP_*_REDIRECT_URI (app builds redirect from Host when APP_PUBLIC_URL_FROM_REQUEST=true).
# On OCI, set APP_PUBLIC_URL_FROM_REQUEST=true in .env — do not rely on APP_PUBLIC_URL in container env.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=lib/terraform-env.sh
source "$PROJECT_ROOT/scripts/oci/lib/terraform-env.sh"
cloud_store_resolve_tf_env "$PROJECT_ROOT"

ENV_FILE="${ENV_FILE:-$PROJECT_ROOT/.env}"
OUT_FILE="$CLOUD_STORE_CONTAINER_ENV_FILE"

KEYS=(
  CLOUDFLARE_TUNNEL_TOKEN
  CLOUDFLARE_TUNNEL_HOSTNAME
  CASHIER_SESSION_SECURE
  APP_PUBLIC_URL
  APP_PUBLIC_URL_FROM_REQUEST
  IDP_SIGNIN_DEBUG
  IDP_POS_ISSUER
  IDP_POS_CLIENT_ID
  IDP_POS_CLIENT_SECRET
  IDP_ADMIN_ISSUER
  IDP_ADMIN_CLIENT_ID
  IDP_ADMIN_CLIENT_SECRET
  IDP_ALLOW_PIN
  CASHIER_SUPERVISOR_APPROVAL
  CASHIER_APPROVAL_TTL_SEC
  IDP_SUPERVISOR_GROUP
  IDP_POS_CASHIER_GROUP
  CASHIER_SUPERVISOR_PIN_IS_SUPERVISOR
  OPENING_CASH_FLOAT
)

read_env() {
  local key="$1"
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: $ENV_FILE not found" >&2
    exit 1
  fi
  local line
  line=$(grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | head -1 || true)
  if [[ -z "$line" ]]; then
    printf ''
    return
  fi
  local val="${line#*=}"
  val="${val#"${val%%[![:space:]]*}"}"
  val="${val%"${val##*[![:space:]]}"}"
  printf '%s' "$val" | tr -d '"' | tr -d "'"
}

to_tf_bool() {
  case "$(echo "$1" | tr '[:upper:]' '[:lower:]')" in
    true|1|yes) echo "true" ;;
    *) echo "false" ;;
  esac
}

to_tf_var_name() {
  echo "$1" | tr '[:upper:]' '[:lower:]'
}

{
  echo "# Generated by scripts/oci/sync-container-env-to-terraform.sh from $ENV_FILE"
  echo "# Environment: $(cloud_store_env_label)"
  echo "# $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Run: CLOUD_STORE_ENV=${CLOUD_STORE_ENV:-prod} ./scripts/oci/terraform-apply-container.sh"
  echo ""

  from_request="$(read_env APP_PUBLIC_URL_FROM_REQUEST)"
  skip_app_url=false
  case "$(echo "$from_request" | tr '[:upper:]' '[:lower:]')" in
    true|1|yes) skip_app_url=true ;;
  esac

  for key in "${KEYS[@]}"; do
    if [[ "$key" == "APP_PUBLIC_URL" && "$skip_app_url" == true ]]; then
      echo "# app_public_url omitted (APP_PUBLIC_URL_FROM_REQUEST=true — OAuth uses request Host on OCI)"
      continue
    fi
    val="$(read_env "$key")"
    tf_name="$(to_tf_var_name "$key")"

    case "$key" in
      IDP_ALLOW_PIN|CASHIER_SUPERVISOR_APPROVAL|CASHIER_SUPERVISOR_PIN_IS_SUPERVISOR|APP_PUBLIC_URL_FROM_REQUEST|IDP_SIGNIN_DEBUG|CASHIER_SESSION_SECURE)
        echo "${tf_name} = $(to_tf_bool "$val")"
        ;;
      CASHIER_APPROVAL_TTL_SEC)
        if [[ -n "$val" ]]; then
          echo "${tf_name} = ${val}"
        fi
        ;;
      *)
        if [[ -n "$val" ]]; then
          # HCL string — escape backslashes and quotes minimally
          esc="${val//\\/\\\\}"
          esc="${esc//\"/\\\"}"
          echo "${tf_name} = \"${esc}\""
        fi
        ;;
    esac
  done
} >"$OUT_FILE"

echo "Wrote $OUT_FILE ($(cloud_store_env_label))"
echo ""

# shellcheck source=lib/oci-ip-warn.sh
source "$PROJECT_ROOT/scripts/oci/lib/oci-ip-warn.sh"

echo "Checking whether terraform apply would replace the container instance..."
set +e
oci_ip_terraform_plan_container_change "$CLOUD_STORE_TF_DIR"
plan_signal=$?
set -e

echo "Next:"
if [[ "$plan_signal" -eq 1 ]]; then
  if [[ "$CLOUD_STORE_ENV" == "dev" ]]; then
    echo "  ./scripts/oci/terraform-apply-container-dev.sh     # apply with IP-change confirmation"
  else
    echo "  ./scripts/oci/terraform-apply-container.sh     # apply with IP-change confirmation"
  fi
else
  if [[ "$CLOUD_STORE_ENV" == "dev" ]]; then
    echo "  ./scripts/oci/terraform-apply-container-dev.sh"
  else
    echo "  ./scripts/oci/terraform-apply-container.sh"
  fi
fi
echo ""
echo "App code only (keeps IP): docker push + ./scripts/oci/restart-container-instance.sh"
