/** ORDS table metadata for /api/admin CRUD. */
const ADMIN_TABLES = {
  products: {
    label: 'Products',
    ords: 'products',
    readOnly: false,
    columns: [
      'id',
      'barcode',
      'name',
      'product_type',
      'manufacturer',
      'price',
      'sale_price',
      'track_inventory',
    ],
    create: [
      'barcode',
      'name',
      'product_type',
      'manufacturer',
      'price',
      'sale_price',
      'track_inventory',
    ],
  },
  product_inventory: {
    label: 'Product inventory',
    ords: 'product_inventory',
    readOnly: false,
    idColumn: 'product_id',
    columns: ['product_id', 'quantity_on_hand', 'reorder_point', 'updated_at'],
    create: ['product_id', 'reorder_point'],
    readOnlyColumns: ['quantity_on_hand', 'updated_at'],
    defaultsOnCreate: (helpers) => ({
      quantity_on_hand: 0,
      updated_at: helpers.ordsTimestamp(),
    }),
  },
  bulk_inventory: {
    label: 'Bulk inventory (kitchen)',
    ords: 'bulk_inventory',
    readOnly: false,
    idColumn: 'sku_key',
    columns: ['sku_key', 'name', 'quantity_on_hand', 'unit', 'reorder_point', 'updated_at'],
    create: ['sku_key', 'name', 'unit', 'reorder_point'],
    readOnlyColumns: ['quantity_on_hand', 'updated_at'],
    defaultsOnCreate: (helpers) => ({
      quantity_on_hand: 0,
      unit: 'oz',
      updated_at: helpers.ordsTimestamp(),
    }),
  },
  inventory_consumption_rules: {
    label: 'Consumption rules',
    ords: 'inventory_consumption_rules',
    readOnly: false,
    idColumn: 'product_type',
    columns: ['product_type', 'bulk_sku_key', 'quantity_per_unit', 'unit'],
    create: ['product_type', 'bulk_sku_key', 'quantity_per_unit', 'unit'],
  },
  inventory_movements: {
    label: 'Inventory movements (read-only)',
    ords: 'inventory_movements',
    readOnly: true,
    columns: [
      'id',
      'product_id',
      'bulk_sku_key',
      'delta',
      'quantity_after',
      'reason',
      'order_number',
      'note',
      'created_at',
    ],
    create: [],
  },
  inventory_status_view: {
    label: 'Inventory status',
    ords: 'inventory_status_view',
    readOnly: true,
    idColumn: 'product_id',
    columns: [
      'product_id',
      'barcode',
      'name',
      'product_type',
      'quantity_on_hand',
      'reorder_point',
      'low_stock',
    ],
    create: [],
  },
  customers: {
    label: 'Customers',
    ords: 'customers',
    readOnly: false,
    columns: [
      'id',
      'name',
      'email',
      'phone',
      'address_line1',
      'address_line2',
      'city',
      'state',
      'postal_code',
      'card_fake',
      'member_code',
    ],
    create: [
      'name',
      'email',
      'phone',
      'address_line1',
      'address_line2',
      'city',
      'state',
      'postal_code',
      'card_fake',
      'member_code',
    ],
  },
  cart_items: {
    label: 'Cart items',
    ords: 'cart_items',
    readOnly: false,
    columns: ['id', 'product_id', 'quantity'],
    create: ['product_id', 'quantity'],
  },
  sales: {
    label: 'Sales',
    ords: 'sales',
    readOnly: false,
    columns: [
      'id',
      'order_number',
      'total',
      'payment_method',
      'customer_id',
      'subtotal_pre_member',
      'member_discount_pre_tax',
      'linked_893',
      'created_at',
    ],
    create: [
      'order_number',
      'total',
      'payment_method',
      'customer_id',
      'subtotal_pre_member',
      'member_discount_pre_tax',
      'linked_893',
      'created_at',
    ],
    defaultsOnCreate: (helpers) => ({
      created_at: helpers.ordsTimestamp(),
      member_discount_pre_tax: 0,
      linked_893: 0,
    }),
  },
  sale_items: {
    label: 'Sale items',
    ords: 'sale_items',
    readOnly: false,
    columns: ['id', 'order_number', 'product_id', 'quantity', 'unit_price', 'line_total'],
    create: ['order_number', 'product_id', 'quantity', 'unit_price', 'line_total'],
  },
  sale_payments: {
    label: 'Sale payments',
    ords: 'sale_payments',
    readOnly: false,
    columns: [
      'id',
      'order_number',
      'sequence_number',
      'payment_method',
      'amount',
      'tendered_amount',
      'change_given',
      'created_at',
    ],
    create: [
      'order_number',
      'sequence_number',
      'payment_method',
      'amount',
      'tendered_amount',
      'change_given',
      'created_at',
    ],
    defaultsOnCreate: (helpers) => ({
      created_at: helpers.ordsTimestamp(),
    }),
  },
  cart_view: {
    label: 'Cart view (read-only)',
    ords: 'cart_view',
    readOnly: true,
    columns: ['id', 'product_id', 'name', 'price', 'sale_price', 'quantity'],
    create: [],
  },
  till_open_approvals: {
    label: 'Till open approval (read-only)',
    ords: 'till_open_approvals',
    readOnly: true,
    columns: [
      'id',
      'status',
      'pos_session_id',
      'cashier_email',
      'cashier_name',
      'till_type',
      'opening_counted_float',
      'expected_opening_float',
      'opening_variance',
      'client_kind',
      'requested_at',
      'expires_at',
      'till_submitted_at',
      'register_id',
      'request_token',
      'cashier_sub',
      'resolved_at',
      'resolved_by_sub',
      'resolved_by_email',
      'deny_reason',
      'opening_denominations',
    ],
    columnLabels: {
      till_type: 'Till type',
      opening_counted_float: 'Opening $',
      expected_opening_float: 'Target $',
      opening_variance: 'Variance $',
      client_kind: 'Client',
      till_submitted_at: 'Till submitted',
      pos_session_id: 'POS session',
    },
    create: [],
  },
  till_close_approvals: {
    label: 'Till close approval (read-only)',
    ords: 'till_close_approvals',
    readOnly: true,
    columns: [
      'id',
      'status',
      'till_id',
      'cashier_email',
      'cashier_name',
      'till_type',
      'expected_close_float',
      'counted_close_float',
      'close_variance',
      'cash_sales_total',
      'change_given_total',
      'opening_counted_float',
      'register_id',
      'close_token',
      'cashier_sub',
      'requested_at',
      'expires_at',
      'resolved_at',
      'resolved_by_sub',
      'resolved_by_email',
      'deny_reason',
      'close_denominations',
    ],
    columnLabels: {
      till_id: 'Till',
      till_type: 'Till type',
      expected_close_float: 'Expected $',
      counted_close_float: 'Counted $',
      close_variance: 'Variance $',
      cash_sales_total: 'Cash sales',
      change_given_total: 'Change given',
      opening_counted_float: 'Opening $',
      close_token: 'Close token',
    },
    create: [],
  },
  tills: {
    label: 'Tills (read-only)',
    ords: 'tills',
    readOnly: true,
    columns: [
      'id',
      'pos_session_id',
      'register_id',
      'cashier_sub',
      'cashier_email',
      'transaction_count',
      'sales_total',
      'cash_total',
      'credit_total',
      'till_type',
      'expected_opening_float',
      'opening_counted_float',
      'opening_variance',
      'open_approval_token',
      'opened_at',
      'closed_at',
      'status',
    ],
    columnLabels: {
      transaction_count: 'Transactions',
      sales_total: 'Sales total',
      cash_total: 'Cash total',
      credit_total: 'Credit total',
      till_type: 'Till type',
      pos_session_id: 'POS session',
    },
    create: [],
  },
};

module.exports = { ADMIN_TABLES };
