/** ORDS table metadata for /api/admin CRUD. */
const ADMIN_TABLES = {
  products: {
    label: 'Products',
    ords: 'products',
    readOnly: false,
    columns: ['id', 'barcode', 'name', 'product_type', 'manufacturer', 'price', 'sale_price'],
    create: ['barcode', 'name', 'product_type', 'manufacturer', 'price', 'sale_price'],
  },
  customers: {
    label: 'Customers',
    ords: 'customers',
    readOnly: false,
    columns: [
      'id',
      'name',
      'email',
      'phone',
      'address_line1',
      'address_line2',
      'city',
      'state',
      'postal_code',
      'card_fake',
      'member_code',
    ],
    create: [
      'name',
      'email',
      'phone',
      'address_line1',
      'address_line2',
      'city',
      'state',
      'postal_code',
      'card_fake',
      'member_code',
    ],
  },
  cart_items: {
    label: 'Cart items',
    ords: 'cart_items',
    readOnly: false,
    columns: ['id', 'product_id', 'quantity'],
    create: ['product_id', 'quantity'],
  },
  sales: {
    label: 'Sales',
    ords: 'sales',
    readOnly: false,
    columns: [
      'id',
      'order_number',
      'total',
      'payment_method',
      'customer_id',
      'subtotal_pre_member',
      'member_discount_pre_tax',
      'linked_893',
      'created_at',
    ],
    create: [
      'order_number',
      'total',
      'payment_method',
      'customer_id',
      'subtotal_pre_member',
      'member_discount_pre_tax',
      'linked_893',
      'created_at',
    ],
    defaultsOnCreate: (helpers) => ({
      created_at: helpers.ordsTimestamp(),
      member_discount_pre_tax: 0,
      linked_893: 0,
    }),
  },
  sale_items: {
    label: 'Sale items',
    ords: 'sale_items',
    readOnly: false,
    columns: ['id', 'order_number', 'product_id', 'quantity', 'unit_price', 'line_total'],
    create: ['order_number', 'product_id', 'quantity', 'unit_price', 'line_total'],
  },
  sale_payments: {
    label: 'Sale payments',
    ords: 'sale_payments',
    readOnly: false,
    columns: [
      'id',
      'order_number',
      'sequence_number',
      'payment_method',
      'amount',
      'tendered_amount',
      'change_given',
      'created_at',
    ],
    create: [
      'order_number',
      'sequence_number',
      'payment_method',
      'amount',
      'tendered_amount',
      'change_given',
      'created_at',
    ],
    defaultsOnCreate: (helpers) => ({
      created_at: helpers.ordsTimestamp(),
    }),
  },
  cart_view: {
    label: 'Cart view (read-only)',
    ords: 'cart_view',
    readOnly: true,
    columns: ['id', 'product_id', 'name', 'price', 'sale_price', 'quantity'],
    create: [],
  },
};

module.exports = { ADMIN_TABLES };
