#!/bin/zsh
# Generate a self-signed TLS cert for OCI Load Balancer HTTPS (POC / bring-up).
#
#   ./scripts/generate-lb-tls.sh oci.cloudstore893.com
#
# Writes terraform/lb_tls.auto.tfvars (gitignored). Then:
#   enable_load_balancer = true in terraform.tfvars
#   cd terraform && terraform apply

set -e

HOST="${1:-oci.cloudstore893.com}"
SCRIPT_DIR="${0:a:h}"
PROJECT_ROOT="${SCRIPT_DIR}/.."
CERT_DIR="${PROJECT_ROOT}/certs/lb"
OUT="${PROJECT_ROOT}/terraform/lb_tls.auto.tfvars"

mkdir -p "$CERT_DIR"

openssl req -x509 -newkey rsa:2048 \
  -keyout "${CERT_DIR}/key.pem" \
  -out "${CERT_DIR}/cert.pem" \
  -days 365 -nodes \
  -subj "/CN=${HOST}"

escape_pem() {
  awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' "$1"
}

CERT_ESC=$(escape_pem "${CERT_DIR}/cert.pem")
KEY_ESC=$(escape_pem "${CERT_DIR}/key.pem")

cat >"$OUT" <<EOF
# Generated by scripts/generate-lb-tls.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Self-signed POC cert for ${HOST}. Browsers will warn until you use a public CA cert.

lb_tls_certificate_pem = "${CERT_ESC}"
lb_tls_private_key_pem   = "${KEY_ESC}"
EOF

echo "✅ Wrote ${OUT}"
echo "Next: set enable_load_balancer = true in terraform.tfvars, then terraform apply"
echo "DNS: point ${HOST} A record at terraform output load_balancer_public_ip"
