#!/usr/bin/env bash
# Point the iOS POS app at the local dev server (same host as npm run dev:up).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/ios-pos/Config/Local.xcconfig"

LAN_URL="$(cd "${ROOT}" && npm run lan-url --silent 2>/dev/null | tr -d '\n' | tr -d '\r')"
if [[ -z "${LAN_URL}" ]]; then
  echo "Could not resolve LAN URL. Set API_BASE_URL manually in ios-pos/Config/Local.xcconfig" >&2
  exit 1
fi

HOSTPATH="${LAN_URL#http://}"
HOSTPATH="${HOSTPATH#https://}"

cat > "${OUT}" <<EOF
// Generated by npm run ios-pos:local-config — local dev server (re-run after LAN IP changes)
API_BASE_URL = http:/\$()/${HOSTPATH}/
EOF

echo "Wrote ${OUT}"
echo "API_BASE_URL → ${LAN_URL}"
echo "Rebuild CloudStorePos in Xcode (Product → Clean Build Folder, then Run)."
