#!/usr/bin/env bash

# Upsert KEY=value in a dotenv file (replace line or append).
idp_env_upsert() {
  local file="$1" key="$2" value="$3"
  local tmp line
  mkdir -p "$(dirname "$file")"
  touch "$file"
  tmp="$(mktemp)"
  line="${key}=${value}"
  if grep -qE "^${key}=" "$file" 2>/dev/null; then
    # shellcheck disable=SC2016
    awk -v k="$key" -v v="$value" 'BEGIN{FS="="; OFS="="} $1==k {print k"="v; next} {print}' "$file" >"$tmp"
  else
    cp "$file" "$tmp"
    printf '\n%s\n' "$line" >>"$tmp"
  fi
  mv "$tmp" "$file"
}

idp_write_state_json() {
  local password="$1"
  jq -nc \
    --arg domainId "$IDP_DOMAIN_ID" \
    --arg domainName "$IDP_DOMAIN_NAME" \
    --arg endpoint "$IDP_DOMAIN_ENDPOINT" \
    --arg issuer "$IDP_ISSUER" \
    --arg email "$IDP_USER_EMAIL" \
    --arg userId "$IDP_USER_ID" \
    --arg posAppId "$IDP_POS_APP_ID" \
    --arg adminAppId "$IDP_ADMIN_APP_ID" \
    --arg createdAt "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    '{
      domainId: $domainId,
      domainName: $domainName,
      endpoint: $endpoint,
      issuer: $issuer,
      userEmail: $email,
      userId: $userId,
      posAppId: $posAppId,
      adminAppId: $adminAppId,
      createdAt: $createdAt
    }' >"$IDP_STATE_FILE"
  chmod 600 "$IDP_STATE_FILE"
  # Password never stored in state file — only printed once at bootstrap.
  unset password
}

idp_write_env_files() {
  echo "==> Writing .env.dev and container env tfvars"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_DEV_USER_EMAIL" "$IDP_USER_EMAIL"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_DEV_DOMAIN_PREFIX" "$IDP_DOMAIN_PREFIX"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_DEV_LICENSE_TYPE" "$IDP_LICENSE_TYPE"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_DOMAIN_ENDPOINT" "$IDP_DOMAIN_ENDPOINT"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_POS_ISSUER" "$IDP_ISSUER"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_POS_CLIENT_ID" "$IDP_POS_CLIENT_ID"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_POS_CLIENT_SECRET" "$IDP_POS_CLIENT_SECRET"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_ADMIN_ISSUER" "$IDP_ISSUER"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_ADMIN_CLIENT_ID" "$IDP_ADMIN_CLIENT_ID"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_ADMIN_CLIENT_SECRET" "$IDP_ADMIN_CLIENT_SECRET"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_ALLOW_PIN" "true"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_SUPERVISOR_GROUP" "$IDP_SUPERVISOR_GROUP"
  idp_env_upsert "$IDP_ENV_FILE" "IDP_POS_CASHIER_GROUP" "$IDP_CASHIER_GROUP"
  idp_env_upsert "$IDP_ENV_FILE" "APP_PUBLIC_URL_FROM_REQUEST" "true"

  # HCL tfvars for sync script / terraform apply
  local out="$CLOUD_STORE_CONTAINER_ENV_FILE"
  {
    echo "# Generated by scripts/oci/idp/bootstrap-dev.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "idp_pos_issuer            = \"${IDP_ISSUER}\""
    echo "idp_pos_client_id         = \"${IDP_POS_CLIENT_ID}\""
    echo "idp_pos_client_secret     = \"${IDP_POS_CLIENT_SECRET}\""
    echo "idp_admin_issuer          = \"${IDP_ISSUER}\""
    echo "idp_admin_client_id       = \"${IDP_ADMIN_CLIENT_ID}\""
    echo "idp_admin_client_secret   = \"${IDP_ADMIN_CLIENT_SECRET}\""
    echo "idp_allow_pin             = true"
    echo "idp_supervisor_group      = \"${IDP_SUPERVISOR_GROUP}\""
    echo "idp_pos_cashier_group     = \"${IDP_CASHIER_GROUP}\""
    echo "app_public_url_from_request = true"
  } >"$out"
  chmod 600 "$out"
  echo "    $IDP_ENV_FILE"
  echo "    $out"
}
